// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApV_1tS7AAgKa-dGnC6Q4Uwd-pACVH5Cw',
    appId: '1:938387022119:android:c8cc2095e615d8d5dbc902',
    messagingSenderId: '938387022119',
    projectId: 'jabolin-331ea',
    databaseURL: 'https://jabolin-331ea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jabolin-331ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkfXMGUok3gMuN38BPSLzJjOgVDvbbfdA',
    appId: '1:938387022119:ios:c6abb657b5cc6f7cdbc902',
    messagingSenderId: '938387022119',
    projectId: 'jabolin-331ea',
    databaseURL: 'https://jabolin-331ea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jabolin-331ea.firebasestorage.app',
    iosBundleId: 'com.example.casaRural1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd0R2jbp2JPmpXELil-hN0Qz3vPr9gDcc',
    appId: '1:938387022119:web:3d1d4abded69d785dbc902',
    messagingSenderId: '938387022119',
    projectId: 'jabolin-331ea',
    authDomain: 'jabolin-331ea.firebaseapp.com',
    databaseURL: 'https://jabolin-331ea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jabolin-331ea.firebasestorage.app',
    measurementId: 'G-375LTC9126',
  );

}